#!/bin/sh

uci set network.wan=interface
uci set network.wan.device='eth0'
uci set network.wan.proto='pppoe'
uci set network.wan.username=''
uci set network.wan.password=''

uci delete network.lan.ip6assign
uci delete network.vpn0
uci delete network.wan6
uci delete network.lan.ipv6
uci delete network.wan.ipv6
uci -q delete network.globals.ula_prefix
uci commit network


uci set dhcp.@dnsmasq[0]=dnsmasq
uci set dhcp.@dnsmasq[0].domainneeded='1'
uci set dhcp.@dnsmasq[0].localise_queries='1'
uci set dhcp.@dnsmasq[0].local='/lan/'
uci set dhcp.@dnsmasq[0].domain='lan'
uci set dhcp.@dnsmasq[0].expandhosts='1'
uci set dhcp.@dnsmasq[0].authoritative='1'
uci set dhcp.@dnsmasq[0].readethers='1'
uci set dhcp.@dnsmasq[0].leasefile='/tmp/dhcp.leases'
uci set dhcp.@dnsmasq[0].localuse='1'
uci set dhcp.@dnsmasq[0].nonwildcard='0'
uci set dhcp.@dnsmasq[0].filter_aaaa='1'
uci set dhcp.@dnsmasq[0].quietdhcp='1'
uci set dhcp.@dnsmasq[0].sequential_ip='1'
uci set dhcp.@dnsmasq[0].filterwin2k='1'
uci set dhcp.@dnsmasq[0].nonegcache='1'
uci set dhcp.@dnsmasq[0].localservice='0'
uci set dhcp.@dnsmasq[0].dns_redirect='0'
uci set dhcp.@dnsmasq[0].rebind_protection='0'
uci set dhcp.@dnsmasq[0].nohosts='1'
uci set dhcp.@dnsmasq[0].resolvfile='/tmp/resolv.conf.d/resolv.conf.auto'
uci set dhcp.@dnsmasq[0].addnhosts='/etc/github_hosts.txt'
uci set dhcp.@dnsmasq[0].cachesize='0'
uci set dhcp.lan=dhcp
uci set dhcp.lan.interface='lan'
uci set dhcp.lan.start='10'
uci set dhcp.lan.leasetime='6h'
uci set dhcp.lan.limit='100'
uci set dhcp.lan.force='1'
uci set dhcp.lan.dhcpv6='disabled'
uci -q delete dhcp.lan.dhcpv6
uci -q delete dhcp.lan.ra
uci commit dhcp


uci -q batch <<-EOF
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'

	delete system.ntp.server
	add_list system.ntp.server="ntp.tencent.com"
	add_list system.ntp.server="cn.ntp.org.cn"
	add_list system.ntp.server="time.apple.com"
	add_list system.ntp.server="time.asia.apple.com"
	add_list system.ntp.server="time1.cloud.tencent.com" 
	add_list system.ntp.server="time2.cloud.tencent.com" 
	add_list system.ntp.server="time3.cloud.tencent.com"
	add_list system.ntp.server="time4.cloud.tencent.com"
	add_list system.ntp.server="time5.cloud.tencent.com"
	add_list system.ntp.server="ntp.aliyun.com"
EOF
uci commit system

uci set luci.diag.dns='wx.qq.com'
uci set luci.diag.ping='wx.qq.com'
uci set luci.diag.route='wx.qq.com'

uci commit luci


exit 0