#!/bin/sh

uci -q batch <<-EOF
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'

	delete system.ntp.server
	add_list system.ntp.server="ntp.tencent.com"
	add_list system.ntp.server="cn.ntp.org.cn"
	add_list system.ntp.server="time.apple.com"
	add_list system.ntp.server="time.asia.apple.com"
	add_list system.ntp.server="ntp.aliyun.com"
EOF
uci commit system

uci set luci.diag.dns='wx.qq.com'
uci set luci.diag.ping='wx.qq.com'
uci set luci.diag.route='wx.qq.com'

uci commit luci

sed -i 's,downloads.openwrt.org,mirrors.tencent.com/lede,g' /etc/opkg/distfeeds.conf

exit 0
