name: Clean

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      artifacts:
        description: 'Cleanup-Old-Artifacts'
        required: false
        default: '15d'
      workflow:
        description: 'Cleanup-Workflow-Runs'
        required: false
        default: '15'
      releases:
        description: 'Cleanup-old-Releases'
        required: false
        default: '15'
  schedule:
    - cron: 0 2 1 * *
    
jobs: 
  Cleanup-Old-Artifacts:
    runs-on: ubuntu-18.04
    steps:
    - name: Cleanup Old Action Artifacts
      uses: kolpav/purge-artifacts-action@v1
      with:
        token: ${{ github.token }}
        expire-in: ${{github.event.inputs.artifacts}}
        
  Cleanup-Workflow-Runs:
    needs: Cleanup-Old-Artifacts
    runs-on: ubuntu-18.04
    steps:
      - name: Cleanup Workflow Runs
        uses: GitRML/delete-workflow-runs@v1.2.1
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: ${{github.event.inputs.workflow}}
 
  Cleanup-old-Releases:
    needs: Cleanup-Workflow-Runs
    runs-on: ubuntu-18.04
    steps:
      - name: Cleanup-old-Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: ${{github.event.inputs.releases}}
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
