name: x86-1806-k5.4

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  # schedule:
    # - cron:  '40 17 * * 0,3'

jobs:
  x86-1806-k54:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Cleanup Workflow Runs
      uses: GitRML/delete-workflow-runs@v1.2.1
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        
    - name: Init Building Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
        TZ: Asia/Shanghai
      run: |
        sudo chmod -R +x $GITHUB_WORKSPACE/scripts/*.sh
        ls -alh $GITHUB_WORKSPACE/scripts/*.sh
        bash $GITHUB_WORKSPACE/scripts/01_init_env.sh
        
    - name: Clone Source
      run: |
        bash $GITHUB_WORKSPACE/scripts/source_code/immortalwrt-18.06-k5.4.sh
        
    - name: Configuration Customization
      id: configuration
      run: |
        bash $GITHUB_WORKSPACE/scripts/02_diy_app.sh
        cat $GITHUB_WORKSPACE/buildinfo/X64/x64-1806-k5.4.buildinfo > /build/immortalwrt/.config
        
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        
    - name: Defconfig
      id: defconfig
      run: |
        bash $GITHUB_WORKSPACE/scripts/03_defconfig.sh x64-1806-k5.4.buildinfo
        
    - name: Deliver buildinfo
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: OpenWrt_buildinfo_x64-k5.4
        path: /build/buildinfo/
        if-no-files-found: ignore
        
    - name: Compile
      id: tools
      run: |
        cd /build/immortalwrt/
        make -j$(($(nproc) + 1)) || make -j1 V=s
        tree bin/
        tree -d bin/
        cd /build/immortalwrt/bin/targets/x86/64 && ls -lSha

    - name: Prepare artifact
      run: |
        bash $GITHUB_WORKSPACE/scripts/04_packaging.sh
        
    - name: Deliver firmware
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: OpenWrt_firmware_x64-k5.4
        path: /build/upload/
        if-no-files-found: ignore
        
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::$(date +%F_%H%M%S)_immortalwrt-18.06-k5.4-x86"
        echo "::set-output name=release_date::$(date +"%F_%H%M%S")"
        touch release.txt
        echo "http://192.168.99.1" > release.txt
        echo "http://immortalwrt.lan" >> release.txt
        echo "::set-output name=TAG_STATUS::success"
        
    - name: Upload firmware to release
      if: steps.tag.outputs.TAG_STATUS == 'success'
      uses: softprops/action-gh-release@v0.1.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ steps.tag.outputs.release_date }}_immortalwrt-18.06-k5.4-x86
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: |
          /build/upload/*
